import { useEffect, useState } from "react";
import { createDepartmentMemory, deleteDepartmentMemory, listDepartmentMemories, updateDepartmentMemory } from "../api/admin";
import type { DepartmentMemoryItem } from "../types";

type Form = { id: string | null; title: string; content: string; enabled: boolean };
const blank: Form = { id: null, title: "", content: "", enabled: true };

export default function DepartmentMemoriesTab({ departmentId }: { departmentId: string }) {
  const [items, setItems] = useState<DepartmentMemoryItem[]>([]); const [form, setForm] = useState<Form | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function refresh() { setLoading(true); try { setItems(await listDepartmentMemories(departmentId)); } catch { setError("加载部门记忆失败"); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, [departmentId]);
  async function save() { if (!form || !form.title.trim() || !form.content.trim()) { setError("标题和内容不能为空"); return; } setSaving(true); setError(""); try { if (form.id) await updateDepartmentMemory(form.id, { title: form.title.trim(), content: form.content.trim(), enabled: form.enabled }); else await createDepartmentMemory(departmentId, { title: form.title.trim(), content: form.content.trim(), enabled: form.enabled }); setForm(null); await refresh(); } catch (e: any) { setError(e?.response?.data?.detail || "保存失败"); } finally { setSaving(false); } }
  async function remove(item: DepartmentMemoryItem) { if (!confirm(`确定删除部门记忆“${item.title}”？`)) return; try { await deleteDepartmentMemory(item.id); await refresh(); } catch { setError("删除失败"); } }
  return <div><div className="flex items-center justify-between mb-4"><p className="text-sm text-slate-400">部门记忆仅用于本部门知识问答 <span className="ml-2">{items.length} / 50</span></p><button disabled={items.length >= 50 || !!form} onClick={() => setForm({ ...blank })} className="rounded-md bg-indigo-600 px-3 py-2 text-xs font-medium text-white disabled:opacity-40">＋ 新增记忆</button></div>{loading ? <p className="text-sm text-slate-400">加载中...</p> : items.length === 0 && !form ? <p className="text-sm text-slate-400">该部门暂无记忆</p> : <div className="bg-white rounded-lg border border-slate-200 divide-y divide-slate-100">{items.map((item) => <div key={item.id} className="p-4"><div className="flex justify-between gap-3"><div className="min-w-0"><p className="font-medium text-slate-800">{item.title}</p><p className="text-sm text-slate-500 whitespace-pre-wrap break-words">{item.content}</p><p className="text-xs text-slate-400 mt-1">{item.enabled ? "已启用" : "已停用"} · 更新于 {new Date(item.updated_at).toLocaleString()}</p></div><div className="shrink-0 flex gap-2"><button aria-label="编辑" title="编辑" onClick={() => setForm({ id: item.id, title: item.title, content: item.content, enabled: item.enabled })} className="text-slate-400 hover:text-indigo-600">✎</button><button aria-label="删除" title="删除" onClick={() => void remove(item)} className="text-slate-400 hover:text-red-600">⌫</button></div></div></div>)}</div>}{form && <div className="mt-3 rounded-md border border-slate-200 bg-white p-4"><div className="flex gap-2"><input className="flex-1 rounded border border-slate-300 px-2 py-1.5 text-sm" placeholder="标题" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></div><textarea maxLength={500} className="mt-2 w-full rounded border border-slate-300 px-2 py-1.5 text-sm" rows={4} placeholder="内容" value={form.content} onChange={(e) => setForm({ ...form, content: e.target.value })} /><div className="flex justify-between mt-1"><label className="text-xs text-slate-500"><input type="checkbox" checked={form.enabled} onChange={(e) => setForm({ ...form, enabled: e.target.checked })} /> <span className="ml-1">启用</span></label><span className="text-xs text-slate-400">{form.content.length} / 500</span></div><div className="flex justify-end gap-2 mt-3"><button onClick={() => setForm(null)} className="px-3 py-1.5 text-xs text-slate-500">取消</button><button disabled={saving} onClick={() => void save()} className="rounded bg-indigo-600 px-3 py-1.5 text-xs text-white disabled:opacity-50">{saving ? "保存中..." : "保存"}</button></div></div>}{error && <p className="mt-3 text-sm text-red-500">{error}</p>}</div>;
}
