import { useState } from "react";
import { askQuestion, confirmAssistantAction, cancelAssistantAction } from "../api/chat";
import AssistantActionCard from "../components/AssistantActionCard";
import type { AssistantActionPreview, AssistantActionResult, PipelineEvent } from "../types";
export default function AdminAssistantPage(){ const [input,setInput]=useState(""); const [events,setEvents]=useState<PipelineEvent[]>([]); const [preview,setPreview]=useState<AssistantActionPreview|null>(null); const [result,setResult]=useState<AssistantActionResult|null>(null); const [busy,setBusy]=useState(false);
 async function ask(){if(!input.trim()||busy)return; setBusy(true); setEvents([]); setPreview(null); setResult(null); try{await askQuestion(input,null,e=>{setEvents(v=>[...v,e]); if(e.node==="action_preview")setPreview(e as unknown as AssistantActionPreview);});}finally{setBusy(false)}}
 async function confirm(){if(!preview)return; const r=await confirmAssistantAction(preview.action_id,preview.confirmation_phrase||"确认执行",preview.parameter_hash||""); setResult(r); if(r.status==="completed")setPreview(null)}
 async function cancel(){if(preview){setResult(await cancelAssistantAction(preview.action_id));setPreview(null)}}
 return <div className="mx-auto max-w-4xl space-y-5"><div><h1 className="text-2xl font-semibold text-slate-900">管理助手</h1><p className="mt-1 text-sm text-slate-500">用自然语言查询企业知识，或发起受控管理操作。</p></div><div className="flex gap-2"><input className="flex-1 rounded-md border border-slate-300 px-3 py-2" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void ask()}} placeholder="例如：查询项目 / action:create_project {...}"/><button className="rounded-md bg-indigo-600 px-4 py-2 text-white" onClick={()=>void ask()} disabled={busy}>发送</button></div>{preview&&<AssistantActionCard action={preview} onConfirm={()=>void confirm()} onCancel={()=>void cancel()} result={result}/>} {result&&!preview&&<div className="rounded-lg border border-slate-200 bg-white p-4 text-sm">操作结果：{result.status}{result.error_code?`（${result.error_code}）`:""}</div>}<div className="space-y-2">{events.filter(e=>e.node!=="action_preview").map((e,i)=><div key={i} className="rounded-lg border border-slate-200 bg-white p-3 text-sm text-slate-700">{e.node}: {e.status}{typeof e.content==="string"?` · ${e.content}`:""}</div>)}</div></div> }
